import fs from "fs";
import os from "os";
import path from "path";
import { enforceExecutionScope } from "../contracts/ExecutionScopeEnforcer";
import { auditManifestPlan } from "../manifest/ManifestAudit";
import { AuthoritativeSourceHydrator } from "../manifest/AuthoritativeSourceHydrator";
import { ValidationCoordinator } from "../orchestration/ValidationCoordinator";
import { CompletionEvaluator } from "../runtime/CompletionEvaluator";
import { AuthorizedCapabilityScope, CapabilityGuard } from "../runtime/CapabilityGuard";
import { VerifiedCheckpointJournal } from "../runtime/VerifiedCheckpointJournal";
import { auditRepairManifestPlan } from "../repair/RepairProposalResolver";
import { ManifestValidator } from "../../services/manifest-validator";
import type { AgentFileChange, ExecutionContract, FileManifest } from "../../types";

describe("Checkpoint 9 manifest demotion", () => {
  let root: string;

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), "cp9-manifest-"));
    fs.mkdirSync(path.join(root, "src"), { recursive: true });
    fs.writeFileSync(path.join(root, "src/a.ts"), "before", "utf8");
  });

  afterEach(() => {
    jest.restoreAllMocks();
    if (fs.existsSync(root)) fs.rmSync(root, { recursive: true, force: true });
  });

  const manifest = (files: FileManifest["files"]): FileManifest => ({
    files, totalFiles: files.length, manifestVersion: "1.0.0",
  });

  const contract = (targetPaths = ["src"]): ExecutionContract => ({
    goal: "Apply deterministic change", taskType: "BUG_FIX", risk: "LOW",
    estimatedComplexity: "SMALL", pipeline: "REPOSITORY", environment: "NODE_JS",
    repositoryRequired: true, expectedFiles: [], validationType: "TYPESCRIPT_BUILD",
    targetPaths, allowedActions: ["create", "modify", "delete"], forbiddenActions: [],
    maxFiles: 5, searchScope: ["src"], contextScope: ["src"], diffCriticEnabled: true,
  });

  function scope(grants: Array<{ path: string; action: "FILE_CREATE" | "FILE_MODIFY" | "FILE_DELETE" }>) {
    const value = AuthorizedCapabilityScope.fromBackendConfiguration({
      workspaceRoot: root, authorityId: "cp9:stage", grants,
    });
    if (!value) throw new Error("fixture scope must be valid");
    return value;
  }

  test("1, 2, 8. manifest requests cannot grant paths or actions and denial causes zero mutation", async () => {
    const planningManifest = manifest([
      { path: "src/a.ts", action: "delete", description: "requested delete", dependencies: [] },
      { path: "src/outside.ts", action: "create", description: "requested create", dependencies: [] },
    ]);
    expect(planningManifest.files).toHaveLength(2);
    const guard = CapabilityGuard.create({
      workspaceRoot: root, scopeId: "stage", authorizedScope: scope([{ path: "src/a.ts", action: "FILE_MODIFY" }]),
    });
    expect(guard.authorize({ path: "src/a.ts", action: "FILE_DELETE", scopeId: "stage" }))
      .toMatchObject({ allowed: false, code: "CAPABILITY_ACTION_NOT_DECLARED" });
    expect(guard.authorize({ path: "src/outside.ts", action: "FILE_CREATE", scopeId: "stage" }))
      .toMatchObject({ allowed: false, code: "CAPABILITY_PATH_NOT_DECLARED" });

    await expect(ValidationCoordinator.applyLocalActionGroup({
      stageId: "stage", localPath: root, authorizedCapabilityScope: scope([{ path: "src/a.ts", action: "FILE_MODIFY" }]),
      changes: [
        { path: "src/a.ts", action: "modify", content: "must roll back", description: "allowed first" },
        { path: "src/outside.ts", action: "create", content: "denied", description: "manifest request" },
      ],
    })).rejects.toMatchObject({ code: "CAPABILITY_PATH_NOT_DECLARED" });
    expect(fs.readFileSync(path.join(root, "src/a.ts"), "utf8")).toBe("before");
    expect(fs.existsSync(path.join(root, "src/outside.ts"))).toBe(false);
  });

  test("3. a structurally valid manifest cannot verify invalid generated bytes", async () => {
    const planningManifest = manifest([
      { path: "src/a.ts", action: "modify", description: "plan", dependencies: [] },
    ]);
    expect(new ManifestValidator(contract(["src/a.ts"]), { existingFiles: ["src/a.ts"] }).validate(planningManifest).valid).toBe(true);
    const journal = new VerifiedCheckpointJournal();
    const originalRead = fs.readFileSync;
    jest.spyOn(fs, "readFileSync").mockImplementation(((file, options?: any) => {
      const value = originalRead.call(fs, file, options);
      return typeof value === "string" && value === "invalid generated code" ? "validation mismatch" : value;
    }) as typeof fs.readFileSync);
    const result = await ValidationCoordinator.applyLocalActionGroup({
      stageId: "stage", localPath: root,
      authorizedCapabilityScope: scope([{ path: "src/a.ts", action: "FILE_MODIFY" }]),
      changes: [{ path: "src/a.ts", action: "modify", content: "invalid generated code", description: "invalid" }],
      journal,
    });
    expect(result.journalEntry.status).toBe("ROLLED_BACK");
    expect(journal.verifiedCheckpoints()).toHaveLength(0);
  });

  test("4, 5. manifest completion prose has no validation or TaskRuntime completion authority", () => {
    const completionSource = fs.readFileSync(path.join(__dirname, "../runtime/CompletionEvaluator.ts"), "utf8");
    const runtimeSource = fs.readFileSync(path.join(__dirname, "../runtime/TaskRuntime.ts"), "utf8");
    expect(completionSource).not.toMatch(/manifest/i);
    expect(runtimeSource).not.toMatch(/manifest/i);
    expect(completionSource).toContain("input.validation.passed");
  });

  test("5, 6. TaskExecutionPlan VERIFIED alone cannot satisfy a completion requirement", () => {
    const plan = {
      stages: [{ id: "stage", status: "VERIFIED", intent: { goal: "model/planner says done" } }],
    } as any;
    expect(CompletionEvaluator.requirementsFromPlan(plan, "revision", new VerifiedCheckpointJournal()))
      .toMatchObject([{ id: "plan-stage:stage", status: "UNSATISFIED", checkpointIds: [] }]);
  });

  test("6. current materialized disk wins over stale manifest-selected context", () => {
    const result = AuthoritativeSourceHydrator.hydrateModifySources(
      manifest([{ path: "src/missing.ts", action: "modify", description: "stale", dependencies: [] }]),
      root,
      ["src/missing.ts"],
      { "src/missing.ts": "stale snapshot claims this exists" },
    );
    expect(result).toMatchObject({ success: false, missingCount: 1 });
    expect(result.mergedSourceMap).toEqual({});
  });

  test("7. actual transaction proposal omitted by manifest is evaluated from disk and contract facts", () => {
    const changes: AgentFileChange[] = [{ path: "src/a.ts", action: "modify", content: "after", description: "actual" }];
    const result = enforceExecutionScope({
      proposedChanges: changes,
      manifest: manifest([{ path: "src/other.ts", action: "modify", description: "plan", dependencies: [] }]),
      contract: contract(["src/a.ts"]),
      existingFilePaths: ["src/a.ts"],
    });
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.manifestObservations).toMatchObject([{ path: "src/a.ts", reason: "UNPLANNED_PATH" }]);
  });

  test("8, 9. dynamic or repair discovery differs from manifest but cannot expand authorization", () => {
    const proposal = [{
      path: "src/discovered.ts", action: "create" as const, content: "candidate", description: "diagnostic candidate",
    }];
    expect(auditRepairManifestPlan(proposal, manifest([
      { path: "src/a.ts", action: "modify", description: "older plan", dependencies: [] },
    ]))).toMatchObject({ valid: false, error: { code: "REPAIR_UNDECLARED_FILE" } });
    expect(CapabilityGuard.create({
      workspaceRoot: root, scopeId: "stage", authorizedScope: scope([{ path: "src/a.ts", action: "FILE_MODIFY" }]),
    }).authorize({ path: "src/discovered.ts", action: "FILE_CREATE", scopeId: "stage" }))
      .toMatchObject({ allowed: false, code: "CAPABILITY_PATH_NOT_DECLARED" });
    const repairSource = fs.readFileSync(path.join(__dirname, "../repair/SelfHealingEngine.ts"), "utf8");
    expect(repairSource).not.toMatch(/approvedManifest\.files\.push|executionContract\.targetPaths\.push/);
  });

  test("9, 11. plan revision cannot rewrite verified journal history and provenance remains available", async () => {
    const journal = new VerifiedCheckpointJournal();
    await ValidationCoordinator.applyLocalActionGroup({
      stageId: "stage", localPath: root,
      authorizedCapabilityScope: scope([{ path: "src/a.ts", action: "FILE_MODIFY" }]),
      changes: [{ path: "src/a.ts", action: "modify", content: "after", description: "executed" }], journal,
    });
    const before = journal.snapshot();
    const mutablePlan = manifest([{ path: "src/a.ts", action: "modify", description: "original rationale", dependencies: [] }]);
    mutablePlan.files = [{ path: "src/revised.ts", action: "create", description: "revised", dependencies: [] }];
    expect(journal.snapshot()).toEqual(before);
    expect(journal.snapshot()[0]).toMatchObject({ status: "VERIFIED", attemptedActions: [{ path: "src/a.ts" }] });
    expect(CompletionEvaluator.requirementsFromPlan({
      stages: [{ id: "stage", status: "PENDING", intent: { goal: "advisory plan status lags" } }],
    } as any, "revision", journal)).toMatchObject([{ status: "SATISFIED" }]);
    expect(auditManifestPlan(
      [{ path: "src/a.ts", action: "modify", content: "after", description: "executed" }],
      manifest([{ path: "src/a.ts", action: "modify", description: "original rationale", dependencies: [] }]),
      () => "modify",
    )).toEqual([]);
  });

  test("10. manifest structural validation remains planning validation", () => {
    const invalid = manifest([{ path: "src/a.ts", action: "invalid" as never, description: "bad", dependencies: [] }]);
    expect(new ManifestValidator(contract(), { existingFiles: ["src/a.ts"] }).validate(invalid).valid).toBe(false);
  });

  test("12-14. production authority constructors and receipt/completion minting do not consume manifest fields", () => {
    const productionRoot = path.resolve(__dirname, "../../..");
    const read = (relative: string) => fs.readFileSync(path.join(productionRoot, relative), "utf8");
    const capability = read("src/ai/runtime/CapabilityGuard.ts");
    const validation = read("src/ai/orchestration/ValidationCoordinator.ts");
    const completion = read("src/ai/runtime/CompletionEvaluator.ts");
    const pipeline = read("src/ai/orchestration/AgentPipeline.ts");
    const codeGenerator = read("src/ai/generation/CodeGenerator.ts");
    const loop = read("src/ai/orchestration/AgentLoopCoordinator.ts");
    const planner = read("src/ai/orchestration/AgentPlanner.ts");
    const controller = read("src/controllers/ai-controller.ts");
    const worktree = read("src/services/git-worktree.service.ts");
    expect(capability).not.toMatch(/from(?:IsolatedWorktree|AuthenticatedProject|BackendConfiguration)\([\s\S]{0,300}manifest/i);
    expect(validation.match(/DeterministicValidationReceipt\.issue\(/g)?.length).toBeGreaterThan(0);
    expect(completion).not.toMatch(/manifest/i);
    expect(pipeline.match(/runtime\.complete\(/g)).toHaveLength(1);
    expect(pipeline).toMatch(/runtime\.complete\(completionEvaluation\.receipt\)/);
    expect(pipeline).toContain("manifestAudit");
    expect(pipeline).toContain('runtime.snapshot().status === "COMPLETED"');
    expect(pipeline).toContain('lifecycleStage: "Determine Completion"');
    expect(pipeline.match(/lifecycleStage: "Done"/g)).toHaveLength(1);
    expect(codeGenerator).not.toContain('mf.action === "delete" && !existingPathsInChanges.has');
    expect(codeGenerator).not.toContain("CODEGEN_MANIFEST_VIOLATION");
    expect(pipeline).not.toContain("APPROVED_MANIFEST_REQUIRED");
    expect(planner).toContain("PLANNING_SCOPE_REJECTED");
    expect(loop).toContain('code.startsWith("PLANNING_")');
    expect(controller).toContain('role: "PLANNING_WORKFLOW_ONLY"');
    expect(worktree).toContain("actualDependencyDelta");
    expect(worktree).not.toContain("agentResponse.changes.map((c) => c.path");
  });
});
